# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 01cb512fb5e9111cc0e018c39a8f488a9204920c145eec179b4fac8ca19c070873a3c2f1a348b43cdc63e91c0fa14d17f71f522301419c6d2e9b926e9677a72f

test:
  secret_key_base: 79932fd27a8222ad8aa547b20822cc5b7482e70dec1362d3e1d0f8d15a15a391b18d51044c41246205bf535a2ba74da215f5f51e2cb2177623d9b2f2f6a6abbf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
